// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagementSystem.Data;

#nullable disable

namespace SalesManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagementSystem.Models.Branch", b =>
                {
                    b.Property<int>("branch_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("branch_id"));

                    b.Property<string>("branch_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mgr_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("mgr_start_date")
                        .HasColumnType("date");

                    b.HasKey("branch_id");

                    b.HasIndex("mgr_id");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_id"));

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<int?>("branch_id")
                        .HasColumnType("int");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("super_id")
                        .HasColumnType("int");

                    b.HasKey("emp_id");

                    b.HasIndex("branch_id");

                    b.HasIndex("super_id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("SalesManagementSystem.Models.Branch", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("mgr_id");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SalesManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("SalesManagementSystem.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("branch_id");

                    b.HasOne("SalesManagementSystem.Models.Employee", "Supervisor")
                        .WithMany()
                        .HasForeignKey("super_id");

                    b.Navigation("Branch");

                    b.Navigation("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
